// /**
//  * Client-side type definitions
//  * Standalone types for frontend applications - no server dependencies
//  * Copy this file to your frontend project and use as needed
//  */

// // ============================================================
// // EXIF DATA TYPES - For Upload
// // ============================================================

// /**
//  * EXIF extra metadata (JSONB field)
//  */
// export interface ExifExtra {
//   whiteBalance?: number;
//   flash?: number;
//   exposureMode?: number;
//   meteringMode?: number;
//   colorSpace?: number;
//   [key: string]: any;
// }

// /**
//  * Complete EXIF data structure matching database schema
//  * Use this type when preparing EXIF data for upload
//  */
// export interface ExifDataUpload {
//   // DO NOT INCLUDE: id, uuid - these are auto-generated by server

//   cameraMake?: string | null;
//   cameraModel?: string | null;
//   lensModel?: string | null;

//   artist?: string | null;
//   copyright?: string | null;
//   software?: string | null;

//   iso?: number | null;

//   shutterSpeed?: string | null;  // e.g., "1/250"
//   aperture?: string | null;       // e.g., "f/2.8"
//   focalLength?: string | null;    // e.g., "50mm"

//   dateTaken?: string | null;      // ISO 8601 date string

//   orientation?: number | null;    // 1-8 (EXIF orientation values)

//   gpsLatitude?: string | null;    // decimal string
//   gpsLongitude?: string | null;   // decimal string
//   gpsAltitude?: string | null;    // decimal string

//   extra?: ExifExtra | null;       // Additional metadata
// }

// // ============================================================
// // API RESPONSE TYPES
// // ============================================================

// /**
//  * Standard API response wrapper
//  */
// export interface ApiResponse<T = any> {
//   success: boolean;
//   message?: string;
//   data?: T;
//   error?: string;
//   statusCode?: number;
// }

// /**
//  * Paginated response
//  */
// export interface PaginatedResponse<T> {
//   success: boolean;
//   count: number;
//   data: T[];
//   pagination: {
//     nextCursor: string | null;
//     hasMore: boolean;
//     limit: number;
//   };
// }

// /**
//  * Page-based pagination response
//  */
// export interface PagePaginatedResponse<T> {
//   success: boolean;
//   count: number;
//   data: T[];
//   pagination: {
//     page: number;
//     pageSize: number;
//     totalPages: number;
//     totalCount: number;
//     hasMore: boolean;
//   };
// }

// // ============================================================
// // IMAGE TYPES WITH EXIF
// // ============================================================

// /**
//  * Image with optional EXIF data
//  */
// export interface ImageWithExif extends Image {
//   exifData?: ExifData | null;
// }

// /**
//  * Result from database join query (images + exif_data)
//  */
// export interface ImageExifJoinResult {
//   images: Image;
//   exif_data: ExifData | null;
// }

// // ============================================================
// // UPLOAD TYPES
// // ============================================================

// /**
//  * Presigned URL response for direct upload to MinIO
//  */
// export interface PresignedUrlResponse {
//   imageUrl: string;
//   thumbnailUrl: string;
// }

// /**
//  * Image metadata for presign request
//  */
// export interface ImagePresignRequest {
//   uuid: string;
//   filename: string;
//   format: string;
//   mimeType: string;
//   fileSize?: number;
//   width?: number;
//   height?: number;
//   hash?: string;
// }

// /**
//  * Upload response
//  */
// export interface UploadResponse {
//   success: boolean;
//   message: string;
//   data: {
//     uploaded: ImageWithExif[];
//     failed: UploadError[];
//     stats: {
//       total: number;
//       successful: number;
//       failed: number;
//       corrupted: number;
//     };
//   };
// }

// export interface UploadError {
//   filename: string;
//   error: string;
//   hash?: string;
// }

// // ============================================================
// // REPLACE IMAGE TYPES
// // ============================================================

// /**
//  * Replace image response
//  */
// export interface ReplaceImageResponse {
//   success: boolean;
//   message: string;
//   data: {
//     image: Image;
//     uploadUrls: {
//       imageUrl: string;
//       thumbnailUrl: string;
//       expiresIn: number;
//     };
//   };
// }

// // ============================================================
// // BATCH OPERATION TYPES
// // ============================================================

// /**
//  * Batch delete response
//  */
// export interface BatchDeleteResponse {
//   success: boolean;
//   message: string;
//   data: {
//     deleted: Image[];
//     failed: BatchOperationError[];
//     stats: {
//       total: number;
//       successful: number;
//       failed: number;
//     };
//   };
// }

// /**
//  * Batch update EXIF response
//  */
// export interface BatchUpdateExifResponse {
//   success: boolean;
//   message: string;
//   data: {
//     updated: ImageWithExif[];
//     failed: BatchOperationError[];
//     stats: {
//       total: number;
//       successful: number;
//       failed: number;
//     };
//   };
// }

// export interface BatchOperationError {
//   uuid: string;
//   error: string;
// }

// // ============================================================
// // EXIF UPDATE TYPES
// // ============================================================

// /**
//  * EXIF update request (client provides only data fields, not id/uuid/timestamps)
//  */
// export type ExifUpdateRequest = Omit<NewExifData, 'id' | 'uuid' | 'createdAt' | 'updatedAt'>;

// /**
//  * Single EXIF update request
//  */
// export interface UpdateExifRequest {
//   uuid: string;
//   exifData: ExifUpdateRequest;
// }

// /**
//  * Batch EXIF update request
//  */
// export interface BatchUpdateExifRequest {
//   updates: Array<{
//     uuid: string;
//     exifData: ExifUpdateRequest;
//   }>;
// }

// // ============================================================
// // SYNC TYPES
// // ============================================================

// /**
//  * Sync operation types
//  */
// export type SyncOperation =
//   | 'upload'
//   | 'download'
//   | 'update'
//   | 'update_exif'
//   | 'delete'
//   | 'replace'
//   | 'conflict'
//   | 'batch_upload'
//   | 'batch_delete'
//   | 'batch_update'
//   | 'batch_update_exif';

// /**
//  * Sync status
//  */
// export type SyncStatus = 'pending' | 'in_progress' | 'completed' | 'failed';

// /**
//  * Sync log entry
//  */
// export interface SyncLogEntry {
//   id: number;
//   syncSequence: number;
//   operation: SyncOperation;
//   imageId: number | null;
//   clientId: string | null;
//   status: SyncStatus;
//   errorMessage: string | null;
//   metadata: Record<string, any> | null;
//   createdAt: Date;
//   completedAt: Date | null;
// }

// /**
//  * Sync response
//  */
// export interface SyncResponse {
//   success: boolean;
//   currentSequence: number;
//   data: Array<{
//     operation: SyncLogEntry;
//     image: ImageWithExif | null;
//   }>;
// }

// // ============================================================
// // IMAGE STATISTICS
// // ============================================================

// export interface ImageStats {
//   totalCount: number;
//   totalSize: number;
//   corruptedCount: number;
//   jpgCount: number;
//   pngCount: number;
//   tifCount: number;
// }

// // ============================================================
// // CLIENT CREATION TYPES (for creating new images)
// // ============================================================

// /**
//  * Client request to create a new image (minimal required fields)
//  */
// export interface CreateImageRequest {
//   uuid?: string; // Optional - server generates if not provided
//   filename: string;
//   format: string;
//   mimeType: string;
//   fileSize?: number;
//   width?: number;
//   height?: number;
//   hash?: string;
// }

// /**
//  * Client request to create image with EXIF data
//  */
// export interface CreateImageWithExifRequest {
//   image: CreateImageRequest;
//   exif?: ExifUpdateRequest;
// }

// // ============================================================
// // UTILITY TYPES
// // ============================================================

// /**
//  * Image status enum
//  */
// export type ImageStatus = 'pending' | 'processing' | 'processed' | 'failed';

// /**
//  * Partial update for images (only updatable fields)
//  */
// export type ImageUpdateFields = Pick<Image, 'filename'>;
